# carbon.compare_opt_closed_formulation { #cflowdist.carbon.compare_opt_closed_formulation }

```python
carbon.compare_opt_closed_formulation(step_flow_data)
```

Compare the result and runtime of the optimization-based formulation and the closed-form by directly solving the linear system for the LL method.

## Parameters {.doc-section .doc-section-parameters}

| Name           | Type            | Description                                                                                 | Default    |
|----------------|-----------------|---------------------------------------------------------------------------------------------|------------|
| step_flow_data | FlowDataWrapper | A FlowDataWrapper object containing all the necessary flow data for the specific time step. | _required_ |

## Returns {.doc-section .doc-section-returns}

| Name   | Type                                          | Description                                                                                                                                                                                                                                           |
|--------|-----------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|        | tuple\[np.ndarray, np.ndarray, float, float\] | A tuple contains: the intensity of ejected flow calculated by the optimization approach, the intensity of ejected flow calculated by the closed-form approach, the runtime of the optimization approach, and the runtime of the closed-form approach. |