# grid.PowerFlowResults { #cflowdist.grid.PowerFlowResults }

```python
grid.PowerFlowResults(tz)
```

A dataclass to wrap and store the power flow results as pandas DataFrames. 
The power flow results include the active power (in MW) for static generators, generators, external grid, loads, lines (from and to), and transformers (HV and LV). 
The DataFrames are indexed by snapshots (with timezone information) and have columns corresponding to the indices of the corresponding elements in the `pandapower` grid (e.g., static generator indices for `p_mw_sgen_df`, generator indices for `p_mw_gen_df`, etc.).
The power flow results are read from CSV files generated by `pandapower` and stored in the `pf_res` directory. The `read_pf_results` function is used to read the CSV files and convert them into pandas DataFrames with the appropriate index and column types.

## Parameters {.doc-section .doc-section-parameters}

| Name   | Type          | Description                                                                                                                                            | Default    |
|--------|---------------|--------------------------------------------------------------------------------------------------------------------------------------------------------|------------|
| tz     | str \| tzinfo | The timezone to be used for the datetime index of the DataFrames. This should match the timezone of the snapshots used in the power flow calculations. | _required_ |

## Attributes {.doc-section .doc-section-attributes}

| Name              | Type         | Description                                                                                                                                                                     |
|-------------------|--------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| p_mw_sgen_df      | pd.DataFrame | A DataFrame containing the active power (in MW) for static generators, indexed by snapshots and with columns corresponding to static generator indices.                         |
| p_mw_gen_df       | pd.DataFrame | A DataFrame containing the active power (in MW) for generators, indexed by snapshots and with columns corresponding to generator indices.                                       |
| p_mw_ext_grid_df  | pd.DataFrame | A DataFrame containing the active power (in MW) for the external grid, indexed by snapshots and with columns corresponding to external grid indices.                            |
| p_mw_load_df      | pd.DataFrame | A DataFrame containing the active power (in MW) for loads, indexed by snapshots and with columns corresponding to load indices.                                                 |
| p_from_mw_line_df | pd.DataFrame | A DataFrame containing the active power (in MW) flowing from the "from" side of lines, indexed by snapshots and with columns corresponding to line indices.                     |
| p_to_mw_line_df   | pd.DataFrame | A DataFrame containing the active power (in MW) flowing from the "to" side of lines, indexed by snapshots and with columns corresponding to line indices.                       |
| p_hv_mw_trafo_df  | pd.DataFrame | A DataFrame containing the active power (in MW) flowing from the high voltage side of transformers, indexed by snapshots and with columns corresponding to transformer indices. |
| p_lv_mw_trafo_df  | pd.DataFrame | A DataFrame containing the active power (in MW) flowing from the low voltage side of transformers, indexed by snapshots and with columns corresponding to transformer indices.  |

## See Also {.doc-section .doc-section-see-also}

- [grid.read_pf_results](/reference/grid.read_pf_results.qmd) : A function that reads power flow results from CSV files generated by `pandapower` and returns them as pandas DataFrames with the appropriate index and column types.