# Function reference {.doc .doc-index}

## cflowdist

| | |
| --- | --- |
| [CarbonTracer](CarbonTracer.qmd#cflowdist.CarbonTracer) | A class to trace carbon flows in the power grid. |
| [read_pickle](read_pickle.qmd#cflowdist.read_pickle) | Read a CarbonTracer object from a pickle file. |

## models

### demand

| | |
| --- | --- |
| [models.demand.naive](models.demand.naive.qmd#cflowdist.models.demand.naive) | Generate naive load profiles based on the rated power of each load in the pandapower grid. The load profile is generated using a simple hourly load factor that varies throughout the day.  |
| [models.demand.p_est_naive](models.demand.p_est_naive.qmd#cflowdist.models.demand.p_est_naive) | A helper function that generates a naive load profile for a single load based on its yearly average power and the hourly load factors defined.  |
| [models.demand.landuse](models.demand.landuse.qmd#cflowdist.models.demand.landuse) | Generate load profiles based on land use data and standard load profiles for different sectors. The function uses the BDEW standard load profiles for electricity demand, which are adjusted based on the annual electricity demand for each load in the pandapower grid.  |

### generation

| | |
| --- | --- |
| [models.generation.primitive](models.generation.primitive.qmd#cflowdist.models.generation.primitive) | Apply the primitive method to generation generator profiles.  |
| [models.generation.p_est_primitive](models.generation.p_est_primitive.qmd#cflowdist.models.generation.p_est_primitive) | A helper function that estimates photovoltaic (PV) power output using a primitive method based on Global Horizontal Irradiance (GHI) data. |
| [models.generation.upgrade_roof](models.generation.upgrade_roof.qmd#cflowdist.models.generation.upgrade_roof) | Apply the upgrade_roof method to compute generation patterns. |
| [models.generation.p_est_upgrade_roof](models.generation.p_est_upgrade_roof.qmd#cflowdist.models.generation.p_est_upgrade_roof) | A helper function that estimates photovoltaic (PV) power output by taking into account roof inclination, orientation, and local weather conditions (GHI, DNI, DHI, temperature, and wind speed) using the pvlib library. |

## roof

| | |
| --- | --- |
| [roof.get_open_meteo](roof.get_open_meteo.qmd#cflowdist.roof.get_open_meteo) | This function is originally provided by [Open-Meteo](https://open-meteo.com/en/docs#historical-weather-api) and adapted for our use case. |
| [roof.find_roof](roof.find_roof.qmd#cflowdist.roof.find_roof) | Find the nearest roof(s) and building (by SB_UUID) to which we can associate the pv plant concerned. |

## grid

| | |
| --- | --- |
| [grid.PowerFlowResults](grid.PowerFlowResults.qmd#cflowdist.grid.PowerFlowResults) | A dataclass to wrap and store the power flow results as pandas DataFrames.  |
| [grid.PowerFlowCalculator](grid.PowerFlowCalculator.qmd#cflowdist.grid.PowerFlowCalculator) | A dataclass to run power flow calculations using `pandapower` and store the results in a `PowerFlowResults` object.  |
| [grid.read_pf_results](grid.read_pf_results.qmd#cflowdist.grid.read_pf_results) | Read power flow results from csv files generated by `pandapower` and return them as pandas DataFrames.  |
| [grid.remove_future_plants](grid.remove_future_plants.qmd#cflowdist.grid.remove_future_plants) | Remove future plants from the grid. This function is used to remove plants that are not yet in operation (according to their `BeginningOfOperation` date) at the start time of the simulation.  |

## network

| | |
| --- | --- |
| [network.ckdnearest](network.ckdnearest.qmd#cflowdist.network.ckdnearest) | Finds the nearest node (bus) to which we can associate the power plant concerned, |
| [network.read_gpkg](network.read_gpkg.qmd#cflowdist.network.read_gpkg) | Read a GeoPackage file and return a dictionary of GeoDataFrames. |
| [network.get_timezone_from_location](network.get_timezone_from_location.qmd#cflowdist.network.get_timezone_from_location) | Get the timezone of a given Location object. |
| [network.find_best_polygon](network.find_best_polygon.qmd#cflowdist.network.find_best_polygon) | Find the polygon in gdf that best matches the point. |
| [network.find_id](network.find_id.qmd#cflowdist.network.find_id) | Find the identifiers of the best matching MV and LV network ID for the location of the tracer, based on the LV and MV hulls in the tracer's data. |
| [network.add_landuse](network.add_landuse.qmd#cflowdist.network.add_landuse) | Add land use category to the bus geodata based on the nearest land use polygon. |
| [network.find_canton](network.find_canton.qmd#cflowdist.network.find_canton) | Find the canton name and code for the location of the tracer using the swisstopo Web API. |

## carbon

| | |
| --- | --- |
| [carbon.FlowDataWrapper](carbon.FlowDataWrapper.qmd#cflowdist.carbon.FlowDataWrapper) | A dataclass to encapsulate all the flow data needed for carbon tracing in a single object, improving code readability and maintainability. |
| [carbon.carrierinit](carbon.carrierinit.qmd#cflowdist.carbon.carrierinit) | Initialize the carbon carrier intensity data for the given tracer. |
| [carbon.create_array](carbon.create_array.qmd#cflowdist.carbon.create_array) | Create a vector or matrix based on given indices and values, |
| [carbon.calculate_Q](carbon.calculate_Q.qmd#cflowdist.carbon.calculate_Q) | Calculate the Q matrix based on the given formula. |
| [carbon.organize_step_flow_data](carbon.organize_step_flow_data.qmd#cflowdist.carbon.organize_step_flow_data) | Organize the power flow data for a specific time step into a structured format (FlowDataWrapper) that can be easily used for carbon tracing calculations. |
| [carbon.post_process_carbon](carbon.post_process_carbon.qmd#cflowdist.carbon.post_process_carbon) | Post-process the carbon intensity and carbon emissions data after allocation, including calculating net carbon intensity, weighted net carbon intensity, and local PV generation aggregated to a LV-net level. |
| [carbon.carbon_tracing_ap](carbon.carbon_tracing_ap.qmd#cflowdist.carbon.carbon_tracing_ap) | Perform carbon tracing (average participation) using an optimization approach to calculate the carbon intensity of the ejected flow and the node emission, with an option to consider self-consumption. (LL method and LL-P method) |
| [carbon.compare_opt_closed_formulation](carbon.compare_opt_closed_formulation.qmd#cflowdist.carbon.compare_opt_closed_formulation) | Compare the result and runtime of the optimization-based formulation and the closed-form by directly solving the linear system for the LL method. |
| [carbon.carbon_tracing_ap_with_losses](carbon.carbon_tracing_ap_with_losses.qmd#cflowdist.carbon.carbon_tracing_ap_with_losses) | Perform carbon tracing (average participation) with the losses allocation to users. (LA method) |
| [carbon.cal_node_flow_with_losses](carbon.cal_node_flow_with_losses.qmd#cflowdist.carbon.cal_node_flow_with_losses) | A standard implementation of the carbon allocation with losses (LA method). |
| [carbon.optimized_node_flow_with_losses](carbon.optimized_node_flow_with_losses.qmd#cflowdist.carbon.optimized_node_flow_with_losses) | Optimized version of `cal_node_flow_with_losses` using sparse matrices and Numba for performance. |

## plot

| | |
| --- | --- |
| [plot.network_plot](plot.network_plot.qmd#cflowdist.plot.network_plot) | Plot network topology by folium, including HV, MV and LV buses, generation plants, as well as MV and LV lines. |
| [plot.network_carbon_plot](plot.network_carbon_plot.qmd#cflowdist.plot.network_carbon_plot) | Plot the calculated node-level carbon intensity using folium. |
| [plot.lv_grids_time_plot](plot.lv_grids_time_plot.qmd#cflowdist.plot.lv_grids_time_plot) | Plot the calculated carbon intensity aggegated to a LV-net level using folium TimeSliderChoropleth, with a time slider. |
| [plot.network_dual_plot](plot.network_dual_plot.qmd#cflowdist.plot.network_dual_plot) | Plot the calculated node-level carbon intensity using folium dual map, comparing two snapshots horizontally, one with light style tile and one with dark style tile. |