# models.generation.p_est_upgrade_roof { #cflowdist.models.generation.p_est_upgrade_roof }

```python
models.generation.p_est_upgrade_roof(
    openmeteo_df,
    loc_selected,
    roof_selected,
    tz,
)
```

A helper function that estimates photovoltaic (PV) power output by taking into account roof inclination, orientation, and local weather conditions (GHI, DNI, DHI, temperature, and wind speed) using the pvlib library.
The function calculates the solar position, plane of array irradiance, cell temperature, and finally the AC power output of the PV system based on the provided weather data and roof characteristics.
The resulting Series contains the estimated power output for each snapshot, indexed by snapshots.

## Parameters {.doc-section .doc-section-parameters}

| Name          | Type         | Description                                                                                                                                               | Default    |
|---------------|--------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------|------------|
| openmeteo_df  | pd.DataFrame | A DataFrame containing local weather data (GHI, DNI, DHI, temperature, and wind speed) indexed by snapshots, generated by `roof.get_open_meteo` function. | _required_ |
| loc_selected  | Location     | The location for which to estimate PV power output.                                                                                                       | _required_ |
| roof_selected | pd.Series    | A Series containing the roof characteristics for the PV system.                                                                                           | _required_ |
| tz            | str          | The timezone of the location, used for time localization of the resulting Series.                                                                         | _required_ |

## Returns {.doc-section .doc-section-returns}

| Name   | Type      | Description                                                                             |
|--------|-----------|-----------------------------------------------------------------------------------------|
|        | pd.Series | A Series containing the estimated power output for each snapshot, indexed by snapshots. |

## See Also {.doc-section .doc-section-see-also}

- [models.generation.primitive](/reference/models.generation.primitive.qmd)
- [models.generation.upgrade_roof](/reference/models.generation.upgrade_roof.qmd)
- [roof.get_open_meteo](/reference/roof.get_open_meteo.qmd) : A function that retrieves local weather data (GHI, DNI, DHI, temperature, and wind speed) for a given location and date range using the Open-Meteo API.