# plot.network_carbon_plot { #cflowdist.plot.network_carbon_plot }

```python
plot.network_carbon_plot(tracer, snapshot, show_colormap=True, show_tools=True)
```

Plot the calculated node-level carbon intensity using folium.

## Parameters {.doc-section .doc-section-parameters}

| Name          | Type         | Description                                                                                                                                    | Default    |
|---------------|--------------|------------------------------------------------------------------------------------------------------------------------------------------------|------------|
| tracer        | CarbonTracer | The CarbonTracer object that contains the constructed network data.                                                                            | _required_ |
| snapshot      | pd.Timestamp | A selected timestamp to plot.                                                                                                                  | _required_ |
| show_colormap | bool         | A boolean flag indicating whether to show a colormap in the map. If True, a colormap will be added to the map.                                 | `True`     |
| show_tools    | bool         | A boolean flag indicating whether to show the tools in the map. If True, a fullscreen button and a geocoder inputbox will be added to the map. | `True`     |

## Returns {.doc-section .doc-section-returns}

| Name   | Type       | Description                                                  |
|--------|------------|--------------------------------------------------------------|
|        | folium.Map | A pretty map visualization of the carbon allocation results. |

## Example {.doc-section .doc-section-example}

```python
tracer.network_carbon_plot(snapshot = tracer.snapshots[0])
```