from dataclasses import dataclass, field
from datetime import tzinfo
import os
import numpy as np
import pandas as pd

import pandapower as pp
import pandapower.control as control
import pandapower.timeseries as timeseries
from pandapower.timeseries.data_sources.frame_data import DFData
from .models import generation, demand

from typing import TYPE_CHECKING, Literal
if TYPE_CHECKING:
    from .core import CarbonTracer

def remove_future_plants(tracer: "CarbonTracer", start_time: pd.Timestamp) -> None:
    """
    Remove future plants from the grid. This function is used to remove plants that are not yet in operation (according to their `BeginningOfOperation` date) at the start time of the simulation. 
    It removes the future plants from the `mv_plant_df` attribute of the tracer, and also removes the corresponding entries from the sgen and gen DataFrames in the `pandapower` grid.

    Parameters
    ----------
    tracer: CarbonTracer
        The CarbonTracer object containing the grid and plant information.
    start_time: pd.Timestamp
        The start time of the simulation, used to determine which plants are considered future plants.
    """
    future_plant_idx = tracer.mv_plant_df[tracer.mv_plant_df['BeginningOfOperation'] > start_time.to_datetime64()].index
    tracer.mv_plant_df.drop(future_plant_idx, inplace=True)
    # sgen
    if hasattr(tracer.pp_grid, 'sgen') and len(tracer.pp_grid.sgen) > 0:
        future_sgen_index = tracer.pp_grid.sgen[tracer.pp_grid.sgen.name.isin(future_plant_idx)].index
        tracer.pp_grid.sgen.drop(future_sgen_index, inplace=True)
    # gen
    if hasattr(tracer.pp_grid, 'gen') and len(tracer.pp_grid.gen) > 0:
        future_gen_index = tracer.pp_grid.gen[tracer.pp_grid.gen.name.isin(future_plant_idx)].index
        tracer.pp_grid.gen.drop(future_gen_index, inplace=True)




def read_pf_results(tz: str | tzinfo) -> list[pd.DataFrame]:
    """
    Read power flow results from csv files generated by `pandapower` and return them as pandas DataFrames. 
    The function reads the active power (in MW) for static generators, generators, external grid, loads, lines (from and to), and transformers (HV and LV) from the corresponding CSV files in the `pf_res` directory. 
    The function also converts the index of each DataFrame to datetime format with timezone information.

    Parameters
    ----------
    tz: str or tzinfo
        The timezone to be used for the datetime index of the DataFrames. This should match the timezone of the snapshots used in the power flow calculations.
    """
    p_mw_sgen_df = pd.read_csv('pf_res/res_sgen/p_mw.csv', index_col=0, sep=';')
    p_mw_sgen_df.index = pd.to_datetime(p_mw_sgen_df.index, utc=True).tz_convert(tz)
    p_mw_sgen_df.columns = p_mw_sgen_df.columns.astype(int)

    p_mw_gen_df = pd.read_csv('pf_res/res_gen/p_mw.csv', index_col=0, sep=';')
    p_mw_gen_df.index = pd.to_datetime(p_mw_gen_df.index, utc=True).tz_convert(tz)
    p_mw_gen_df.columns = p_mw_gen_df.columns.astype(int)

    p_mw_load_df = pd.read_csv('pf_res/res_load/p_mw.csv', index_col=0, sep=';')
    p_mw_load_df.index = pd.to_datetime(p_mw_load_df.index, utc=True).tz_convert(tz)
    p_mw_load_df.columns = p_mw_load_df.columns.astype(int)

    p_from_mw_line_df = pd.read_csv('pf_res/res_line/p_from_mw.csv', index_col=0, sep=';')
    p_from_mw_line_df.index = pd.to_datetime(p_from_mw_line_df.index, utc=True).tz_convert(tz)
    p_from_mw_line_df.columns = p_from_mw_line_df.columns.astype(int)

    p_to_mw_line_df = pd.read_csv('pf_res/res_line/p_to_mw.csv', index_col=0, sep=';')
    p_to_mw_line_df.index = pd.to_datetime(p_to_mw_line_df.index, utc=True).tz_convert(tz)
    p_to_mw_line_df.columns = p_to_mw_line_df.columns.astype(int)

    p_hv_mw_trafo_df = pd.read_csv('pf_res/res_trafo/p_hv_mw.csv', index_col=0, sep=';')
    p_hv_mw_trafo_df.index = pd.to_datetime(p_hv_mw_trafo_df.index, utc=True).tz_convert(tz)
    p_hv_mw_trafo_df.columns = p_hv_mw_trafo_df.columns.astype(int)

    p_lv_mw_trafo_df = pd.read_csv('pf_res/res_trafo/p_lv_mw.csv', index_col=0, sep=';')
    p_lv_mw_trafo_df.index = pd.to_datetime(p_lv_mw_trafo_df.index, utc=True).tz_convert(tz)
    p_lv_mw_trafo_df.columns = p_lv_mw_trafo_df.columns.astype(int)

    p_mw_ext_grid_df = pd.read_csv('pf_res/res_ext_grid/p_mw.csv', index_col=0, sep=';')
    p_mw_ext_grid_df.index = pd.to_datetime(p_mw_ext_grid_df.index, utc=True).tz_convert(tz)
    p_mw_ext_grid_df.columns = p_mw_ext_grid_df.columns.astype(int)
    return [p_mw_sgen_df,p_mw_gen_df, p_mw_ext_grid_df, p_mw_load_df, p_from_mw_line_df, p_to_mw_line_df, p_hv_mw_trafo_df, p_lv_mw_trafo_df]


@dataclass
class PowerFlowResults:
    """
    A dataclass to wrap and store the power flow results as pandas DataFrames. 
    The power flow results include the active power (in MW) for static generators, generators, external grid, loads, lines (from and to), and transformers (HV and LV). 
    The DataFrames are indexed by snapshots (with timezone information) and have columns corresponding to the indices of the corresponding elements in the `pandapower` grid (e.g., static generator indices for `p_mw_sgen_df`, generator indices for `p_mw_gen_df`, etc.).
    The power flow results are read from CSV files generated by `pandapower` and stored in the `pf_res` directory. The `read_pf_results` function is used to read the CSV files and convert them into pandas DataFrames with the appropriate index and column types.

    Parameters
    ----------
    tz: str or tzinfo
        The timezone to be used for the datetime index of the DataFrames. This should match the timezone of the snapshots used in the power flow calculations.
    
    Attributes
    ----------
    p_mw_sgen_df: pd.DataFrame
        A DataFrame containing the active power (in MW) for static generators, indexed by snapshots and with columns corresponding to static generator indices.
    p_mw_gen_df: pd.DataFrame
        A DataFrame containing the active power (in MW) for generators, indexed by snapshots and with columns corresponding to generator indices.
    p_mw_ext_grid_df: pd.DataFrame
        A DataFrame containing the active power (in MW) for the external grid, indexed by snapshots and with columns corresponding to external grid indices.
    p_mw_load_df: pd.DataFrame
        A DataFrame containing the active power (in MW) for loads, indexed by snapshots and with columns corresponding to load indices.
    p_from_mw_line_df: pd.DataFrame
        A DataFrame containing the active power (in MW) flowing from the "from" side of lines, indexed by snapshots and with columns corresponding to line indices.
    p_to_mw_line_df: pd.DataFrame
        A DataFrame containing the active power (in MW) flowing from the "to" side of lines, indexed by snapshots and with columns corresponding to line indices.
    p_hv_mw_trafo_df: pd.DataFrame
        A DataFrame containing the active power (in MW) flowing from the high voltage side of transformers, indexed by snapshots and with columns corresponding to transformer indices.
    p_lv_mw_trafo_df: pd.DataFrame
        A DataFrame containing the active power (in MW) flowing from the low voltage side of transformers, indexed by snapshots and with columns corresponding to transformer indices.
    
    See Also
    --------
    - [grid.read_pf_results](/reference/grid.read_pf_results.qmd) : A function that reads power flow results from CSV files generated by `pandapower` and returns them as pandas DataFrames with the appropriate index and column types.
    """
    tz: str | tzinfo
    p_mw_sgen_df: pd.DataFrame = field(init=False)
    p_mw_gen_df: pd.DataFrame = field(init=False)
    p_mw_ext_grid_df: pd.DataFrame = field(init=False)
    p_mw_load_df: pd.DataFrame = field(init=False)
    p_from_mw_line_df: pd.DataFrame = field(init=False) 
    p_to_mw_line_df: pd.DataFrame = field(init=False)
    p_hv_mw_trafo_df: pd.DataFrame = field(init=False)
    p_lv_mw_trafo_df: pd.DataFrame = field(init=False)

    def __post_init__(self):
        pf_results = read_pf_results(tz=self.tz)
        self.p_mw_sgen_df, self.p_mw_gen_df, self.p_mw_ext_grid_df, self.p_mw_load_df, self.p_from_mw_line_df, self.p_to_mw_line_df, self.p_hv_mw_trafo_df, self.p_lv_mw_trafo_df = pf_results


@dataclass
class PowerFlowCalculator:
    """
    A dataclass to run power flow calculations using `pandapower` and store the results in a `PowerFlowResults` object. 
    The `PowerFlowCalculator` takes a `CarbonTracer` object as input, which contains the `pandapower` grid and the snapshots to be used for the power flow calculations.
    The `PowerFlowCalculator` runs the power flow calculations for each snapshot using `pandapower`'s time series simulation capabilities, and stores the results in a `PowerFlowResults` object.
    The power flow results are saved to CSV files in the `pf_res` directory, and can be read back into pandas DataFrames using the `read_pf_results` function.

    Parameters
    ----------
    tracer: CarbonTracer
        The CarbonTracer object containing the `pandapower` grid and the snapshots to be used for the power flow calculations.
    
    Attributes
    ----------
    pp_grid: pandapowerNet
        The `pandapower` grid extracted from the `CarbonTracer` object, which is used for the power flow calculations.
    snapshots: pd.DatetimeIndex
        The snapshots extracted from the `CarbonTracer` object, which are used as time steps for the power flow calculations.
    pf_results: PowerFlowResults
        The power flow results stored in a `PowerFlowResults` object, which contains the active power (in MW) for static generators, generators, external grid, loads, lines (from and to), and transformers (HV and LV) as pandas DataFrames indexed by snapshots and with columns corresponding to the indices of the corresponding elements in the `pandapower` grid.
    
    See Also
    --------
    - [grid.PowerFlowResults](/reference/grid.PowerFlowResults.qmd) : A dataclass to wrap and store the power flow results as pandas DataFrames.
    """
    tracer: "CarbonTracer"
    pp_grid: pp.pandapowerNet = field(init=False)
    snapshots: pd.DatetimeIndex = field(init=False)
    pf_results: PowerFlowResults = field(init=False)

    def __post_init__(self):
        assert type(self.tracer.pp_grid) is pp.pandapowerNet, "Tracer must have a pandapower grid to run power flow calculations."
        self.pp_grid = self.tracer.pp_grid#copy.deepcopy(self.tracer.pp_grid)
        assert self.tracer.snapshots is not None, "Tracer must have snapshots to run power flow calculations."
        self.snapshots = self.tracer.snapshots

    def run_power_flow(self) -> None:
        """
        Run power flow (by pandapower time series simulation).
        """

        pp_grid = self.pp_grid
        snapshots = self.snapshots
        # timeseries analysis in pandapower
        self.load_p_mw_t = self.model_demand(method='landuse')
        self.sgen_p_mw_t = self.model_sgen(method='upgrade_roof')
        if len(self.pp_grid.gen) >0:
            self.gen_p_mw_t = self.model_gen(method='upgrade_roof')
        # initialising the outputwriter to save data to excel files in the current folder. You can change this to .json, .csv, or .pickle as well
        if not os.path.exists(self.tracer.path_dict['pf_results']):
            os.makedirs(self.tracer.path_dict['pf_results'])
        ow = timeseries.OutputWriter(pp_grid, output_path=self.tracer.path_dict['pf_results'], output_file_type=".csv")
        # adding vm_pu of all buses and line_loading in percent of all lines as outputs to be stored
        ow.log_variable('res_sgen', 'p_mw')
        ow.log_variable('res_gen', 'p_mw')
        ow.log_variable('res_load', 'p_mw')
        ow.log_variable('res_line', 'p_from_mw')
        ow.log_variable('res_line', 'p_to_mw')
        ow.log_variable('res_trafo', 'p_hv_mw')
        ow.log_variable('res_trafo', 'p_lv_mw')
        ow.log_variable('res_ext_grid', 'p_mw')
        timeseries.run_timeseries(pp_grid, time_steps=snapshots, run=pp.runpp)

        pp.runpp(pp_grid)
        self.is_converged = True
        tz = self.snapshots.tz
        assert tz is not None, "Snapshots must have timezone information."
        self.pf_results = PowerFlowResults(tz = tz)

    def model_demand(self, method: Literal['naive', 'landuse'] = 'landuse') -> pd.DataFrame:
        """
        Set demand patterns for each node in the network (by pandapower's const controller).

        Parameters
        ----------
        method: str, default 'landuse'
            The method to be used to model the demand. Currently support `'naive'` and `'landuse'` demand models.

             - `'naive'`: assign the same demand pattern (load factor) to all nodes
             - `'landuse'`: assign different demand patterns to nodes based on their landuse type
        
        Returns
        -------
        loads_p_mw_t: pd.DataFrame
            A dataframe with the active power demand (in MW) for each node (bus) and each time step (snapshot). 
        """
        if method not in ['naive', 'landuse']:
            raise Exception("Currently only support 'naive' and 'landuse' demand models.")
        n_ts = len(self.snapshots)
        snapshots = self.snapshots
        pp_grid = self.pp_grid

        if method == 'naive':
            print('Demand model: naive model')
            selected_method = getattr(demand, method) # select the method to be used to model the demand
            loads_p_mw_t = pd.DataFrame(index=snapshots, columns=pp_grid.load.index, data=np.zeros((n_ts, pp_grid.load.shape[0])))
            loads_p_mw_t = selected_method(loads_p_mw_t ,snapshots=snapshots, df_load = pp_grid.load)
            
        elif method == 'landuse':
            print('Demand model: landuse model')
            pp_grid.load['load_type'] = pp_grid.bus.load_type[pp_grid.load.bus].values
            selected_method = getattr(demand, method)
            loads_p_mw_t = selected_method(snapshots, pp_grid, self.tracer)


        ds_load = DFData(loads_p_mw_t)
        const_load = control.ConstControl(pp_grid, element='load', variable='p_mw', element_index=pp_grid.load.index, data_source=ds_load, profile_name=pp_grid.load.index)
        return loads_p_mw_t
    

    def model_sgen(self, method: Literal['upgrade_roof', 'primitive'] ='upgrade_roof') -> pd.DataFrame:
        """
        Set static generators' (PQ controlled nodes) patterns for each node in the network (by pandapower's const controller).

        Parameters
        ----------
        method: str, default 'upgrade_roof'
            The method to be used to model the static generators. Currently support `'primitive'` and `'upgrade_roof'` generation models.

             - `'primitive'`: assign the same generation pattern (generation factor) to all static generators
             - `'upgrade_roof'`: assign different generation patterns to static generators based on the roof area of the buildings at the location of the static generator. This model is only applicable for grids in Switzerland, as it relies on a dataset of roof areas in Switzerland.
        Returns
        -------
        sgen_p_mw_t: pd.DataFrame
            A dataframe with the active power generation (in MW) for each static generator and each time step (snapshot).
        """
        if method not in ['upgrade_roof', 'primitive']:
            raise Exception("Please choose between 'primitive' and 'upgrade_roof' for generation models.")
        
        snapshots = self.snapshots
        pp_grid = self.pp_grid
        
        n_ts = len(snapshots)
        sgen_p_mw_t = pd.DataFrame(index=snapshots, columns=pp_grid.sgen.index, data=np.zeros((n_ts, pp_grid.sgen.shape[0])))

        selected_method = getattr(generation, method) # select the method to be used to model the generation
        if method == 'primitive':
            print('Generation model: primitive')
            sgen_p_mw_t = selected_method(sgen_p_mw_t, pp_grid.sgen, snapshots)
        elif method == 'upgrade_roof':
            print('Generation model: upgrade roof')
            sgen_p_mw_t = selected_method(sgen_p_mw_t, pp_grid.sgen, snapshots, self.tracer)
        ds_sgen = DFData(sgen_p_mw_t)
        const_sgen = control.ConstControl(pp_grid, element='sgen', variable='p_mw', element_index=pp_grid.sgen.index, data_source=ds_sgen, profile_name=pp_grid.sgen.index)
        return sgen_p_mw_t
    def model_gen(self, method: Literal['upgrade_roof', 'primitive'] ='upgrade_roof') -> pd.DataFrame:
        """
        Set generators' (PV controlled nodes) patterns for each node in the network (by pandapower's const controller).

        Parameters
        ----------
        method: str, default 'upgrade_roof'
            The method to be used to model the generators. Currently support `'primitive'` and `'upgrade_roof'` generation models.
            
             - `'primitive'`: assign the same generation pattern (generation factor) to all generators
             - `'upgrade_roof'`: assign different generation patterns to generators based on the roof area of the buildings at the location of the generator. This model is only applicable for grids in Switzerland, as it relies on a dataset of roof areas in Switzerland.
        Returns
        -------
        gen_p_mw_t: pd.DataFrame
            A dataframe with the active power generation (in MW) for each generator and each time step (snapshot).
        """
        if method not in ['upgrade_roof', 'primitive']:
            raise Exception("Please choose between 'primitive' and 'upgrade_roof' for generation models.")
        
        snapshots = self.snapshots
        pp_grid = self.pp_grid
        
        n_ts = len(snapshots)
        gen_p_mw_t = pd.DataFrame(index=snapshots, columns=pp_grid.gen.index, data=np.zeros((n_ts, pp_grid.gen.shape[0])))

        selected_method = getattr(generation, method) # select the method to be used to model the generation
        if method == 'primitive':
            gen_p_mw_t = selected_method(gen_p_mw_t, pp_grid.gen, snapshots)
        elif method == 'upgrade_roof':
            gen_p_mw_t = selected_method(gen_p_mw_t, pp_grid.gen, snapshots, self.tracer)
        ds_gen = DFData(gen_p_mw_t)
        const_gen = control.ConstControl(pp_grid, element='gen', variable='p_mw', element_index=pp_grid.gen.index, data_source=ds_gen, profile_name=pp_grid.gen.index)
        return gen_p_mw_t