project:
  type: website
  output-dir: ../docs
  preview: 
    port: 1218

execute: 
  freeze: auto

website:
  title: "CFlowDist Documentation"
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: reference/index.qmd
        text: Reference
      - href: presentation/index.qmd
        text: Presentation
  page-footer:
    left: |
      <span class="faux-block"> <i class="bi bi-c-circle"></i>  2026 Distributed Electrical Systems Laboratory  </span>
      <span class="faux-block">Licensed under GNU General Public License v3.0</span>
    
    right: |
      <span class="faux-block">  Made at 
      <svg id="epfl-logo" data-name="logo epfl 2019" xmlns="http://www.w3.org/2000/svg" style="height: 1em; width: auto; vertical-align: middle;" viewBox="0 0 182.4 53" fill="currentColor">
          <polygon points="0 21.6 11.43 21.6 11.43 9.8 38.34 9.8 38.34 0 0 0 0 21.6"/>
          <polygon points="0 53 38.34 53 38.34 43.2 11.43 43.2 11.43 31.4 0 31.4 0 53"/>
          <rect x="11.43" y="21.6" width="24.61" height="9.8"/>
          <path d="M86,4.87a16.12,16.12,0,0,0-5.68-3.53A23.76,23.76,0,0,0,71.82,0H48.14V53H59.57V31.4H71.82a23.76,23.76,0,0,0,8.46-1.34A16.12,16.12,0,0,0,86,26.53a13.43,13.43,0,0,0,3.19-5,17.38,17.38,0,0,0,0-11.62A13.52,13.52,0,0,0,86,4.87ZM78,18.73a5.7,5.7,0,0,1-2.26,1.8,11.33,11.33,0,0,1-3.27.85,32,32,0,0,1-3.86.22H59.57V9.8h9.05a32,32,0,0,1,3.86.22,11,11,0,0,1,3.27.86A5.59,5.59,0,0,1,78,12.67a5,5,0,0,1,.86,3A5,5,0,0,1,78,18.73Z"/>
          <polygon points="155.47 43.2 155.47 0 144.04 0 144.04 53 182.38 53 182.38 43.2 155.47 43.2"/>
          <polygon points="97.42 21.6 108.85 21.6 108.85 9.8 135.76 9.8 135.76 0 97.42 0 97.42 21.6"/>
          <rect x="97.42" y="31.4" width="11.43" height="21.6"/>
          <rect x="108.85" y="21.6" width="24.61" height="9.8"/>
        </svg>
      </span>
      <span class="faux-block">Built with [Quarto](https://quarto.org/) & [Quartodoc](https://machow.github.io/quartodoc)</span>


format:
  html:
    theme: 
      - style.scss
    toc: true
    toc-depth: 3
    highlight-style: github
    email-obfuscation: javascript

  
metadata-files:
  - _sidebar.yml

quartodoc:
  package: cflowdist
  dir: reference        # Where .qmd files for functions/classes will go
  sidebar: "_sidebar.yml"  # Custom sidebar file for the reference section
  sections:
    - title: cflowdist
      contents:
        - CarbonTracer
        - read_pickle
    - title: models
    - subtitle: demand
      contents:
        - models.demand.naive
        - models.demand.p_est_naive
        - models.demand.landuse
    - subtitle: generation
      contents:
        - models.generation.primitive
        - models.generation.p_est_primitive
        - models.generation.upgrade_roof
        - models.generation.p_est_upgrade_roof
    - title: roof
      contents:
        - roof.get_open_meteo
        - roof.find_roof
    - title: grid
      contents:
        - grid.PowerFlowResults
        - grid.PowerFlowCalculator
        - grid.read_pf_results
        - grid.remove_future_plants
    - title: network
      contents:
        - network.ckdnearest
        - network.read_gpkg
        - network.get_timezone_from_location
        - network.find_best_polygon
        - network.find_id
        - network.add_landuse
        - network.find_canton
    - title: carbon
      contents:
        - carbon.FlowDataWrapper
        - carbon.carrierinit
        - carbon.create_array
        - carbon.calculate_Q
        - carbon.organize_step_flow_data
        - carbon.post_process_carbon
        - carbon.carbon_tracing_ap
        - carbon.compare_opt_closed_formulation
        - carbon.carbon_tracing_ap_with_losses
        - carbon.cal_node_flow_with_losses
        - carbon.optimized_node_flow_with_losses
    - title: plot
      contents:
        - plot.network_plot
        - plot.network_carbon_plot
        - plot.lv_grids_time_plot
        - plot.network_dual_plot
